<?php include $phireHeader; ?>
    <h1 class="content-header"><?=$title; ?> : <span id="title-span"><?=$content_type_name; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content-types', 'add')): ?>
        <nav><a href="<?=$phireUri . '/content/types/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/content/types'; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
