<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>

<body>
    <h1><?=$title; ?></h1>
<?php if (count($items) > 0): ?>
<?=$pages; ?>
<?php foreach ($items as $item): ?>
    <div class="date-div">
        <h4><a href="<?=$item->uri; ?>"><?=$item->title; ?></a></h4>
        <h5><?=date($config->datetime_format, strtotime($item->publish)); ?></h5>
<?php if (!empty($item->content)): ?>
        <p><?=strip_tags($item->content); ?></p>
<?php endif; ?>
    </div>
<?php endforeach; ?>
<?php endif; ?>
</body>

</html>
