<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>

<body>
    <h1><?=$title; ?></h1>
<?php if (count($rows) > 0): ?>
<?php foreach ($rows as $row): ?>
    <div class="date-div">
        <h4><a href="<?=$row->uri; ?>"><?=$row->title; ?></a></h4>
        <h5><?=date($config->datetime_format, strtotime($row->publish)); ?></h5>
<?php if (!empty($row->content)): ?>
        <p><?=strip_tags($row->content); ?></p>
<?php endif; ?>
    </div>
<?php endforeach; ?>
<?php endif; ?>
</body>

</html>
