<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="none" />

    <style type="text/css">
        html, body {
            font-family: arial, sans-serif;
            font-size: 0.9em;
        }
    </style>

</head>

<body>
    <h1 style="color: #f00;"><a href="/"><?=$title; ?></a></h1>
    <p>Sorry, that page was not found.</p>
</body>

</html>
