<?php include $phireHeader; ?>
        <h1 id="navigation-title" data-title="<?php echo (isset($data_title) ? $data_title : null); ?>"><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if ($acl->isAuth('Content\Controller\Structure\NavigationController', 'add')): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/structure/navigation/add">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($form)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/structure/navigation"><?php $i18n->_e('Back'); ?></a>
<?php echo $form;
elseif (isset($navigation) && isset($navigation[0])): ?>
            <table class="data-table" cellpadding="0" cellspacing="0" border="0">
                <tr><th class="first-th"><a href="<?php echo BASE_PATH . APP_URI; ?>/structure/navigation?sort=id">#</a></th><th style="width: 5%; text-align: center;"><?php echo (($acl->isAuth('Content\Controller\Structure\NavigationController', 'edit')) ? $i18n->__('Edit') : '&nbsp;'); ?></th><th><a href="<?php echo BASE_PATH . APP_URI; ?>/structure/navigation?sort=navigation"><?php $i18n->_e('Navigation'); ?></a></th><th class="last-th">&nbsp;</th></tr>
<?php foreach ($navigation as $nav):
    $navDiv = null;
    $expand = ($acl->isAuth('Content\Controller\Structure\NavigationController', 'edit')) ? '<a href="#" onclick="$(\'#nav-div-' . $nav['nav']->id . '\').toggle(); return false;">[+]&nbsp;' . $nav['nav']->navigation . '</a>' : $nav['nav']->navigation;
    $remove = ($acl->isAuth('Content\Controller\Structure\NavigationController', 'process')) ?
        '<input type="checkbox" name="remove_navigation[]" id="remove_navigation1" value="' . $nav['nav']->id . '" />' : '&nbsp;';
    $edit = ($acl->isAuth('Content\Controller\Structure\NavigationController', 'edit')) ?
        '<a class="edit-link" title="' . $i18n->__('Edit') . '" href="' . BASE_PATH . APP_URI .'/structure/navigation/edit/' . $nav['nav']->id . '">Edit</a>' : '&nbsp;';

    if ($acl->isAuth('Content\Controller\Structure\NavigationController', 'edit')):
        $navDiv = '<div style="display: none;" id="nav-div-' . $nav['nav']->id . '" class="nav-div">' . ((count($nav['children']) > 0) ? '<strong>' . $i18n->__('Parent') . ' / ' . $i18n->__('Order') . '</strong>' : null) .'<br />';
        $navDiv .= '<form action="' . BASE_PATH . APP_URI . '/structure/navigation/process/' . $nav['nav']->id . '" method="post">';
        foreach ($nav['children'] as $c):
            $parents = ($c['isCategory']) ? $nav['catParents'] : $nav['contParents'];
            $prefix = ($c['isCategory']) ? 'cat_' : 'cont_';
            unset($parents[$c['content_id']]);
            if (count($c['children']) > 0):
                foreach ($c['children'] as $cId):
                    if (array_key_exists($cId, $parents)):
                        unset($parents[$cId]);
                    endif;
                endforeach;
            endif;
            $select = new \Pop\Form\Element\Select($prefix . 'parent_id_' . $c['content_id'], $parents, $c['parent_id']);
            $select->setAttributes('style', 'padding: 1px; margin: 2px 2px 2px 0; width: 180px;');
            $navDiv .= '<div style="margin: 6px 0 6px 0;">' . $select . '<input type="text" style="margin: 0 5px 0 0; padding: 2px; font-size: 1.0em; text-align: center;" name="' . $prefix . 'navigation_order_' . $c['navigation_id'] . '_' . $c['content_id'] . '" size="2" value="' . $c['order'] . '" /> ' . $c['title'] . '</div>';
        endforeach;
        $navDiv .= '<input style="float: left; width: 90px; font-size: 10px; padding-top: 3px; height: 20px;" class="small-save-btn" type="submit" name="submit" value="' . $i18n->__('Process') . '" /> <input style="float: left; margin: 3px 5px 0 15px;" type="checkbox" name="rm_nav" value="' . $nav['nav']->id . '" /> <span style="float: left; margin: 4px 0 0 0;">' . $i18n->__('Remove') . '?</span></form></div>';
    endif;
?>
                <tr><td class="first-td vert-top"><?php echo $nav['nav']->id; ?></td><td class="vert-top" style="width: 5%; text-align: center;"><?php echo $edit; ?></td><td class="vert-top"><?php echo $expand . $navDiv; ?></td><td class="last-td vert-top">&nbsp;</td></tr>
<?php endforeach; ?>
                <tr class="table-bottom-row"><td colspan="4" class="table-bottom-row"><div class="page-links"></div></td></tr>
            </table>
<?php else: ?>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There is currently no navigation.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>
