<?php include $phireHeader; ?>
        <h1 id="template-title" data-title="<?php echo (isset($data_title) ? $data_title : null); ?>"><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if ($acl->isAuth('Content\Controller\Structure\TemplatesController', 'add')): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/structure/templates/add">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($form)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/structure/templates"><?php $i18n->_e('Back'); ?></a>
<?php echo $form;
elseif (isset($table)): ?>
<?php echo $table;
else: ?>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There are currently no templates.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>