<!DOCTYPE html>
<html>

<head>

    <title><?=$systemTitle; ?> : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link type="image/png" rel="shortcut icon" href="<?=$contentPath; ?>/assets/<?=(isset($config) && isset($config['system_theme'])) ? $config['system_theme'] : 'default'; ?>/img/phire-icon.png"  />
    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
<?php if (count($assets['css']['link']) > 0): ?>
<?php foreach ($assets['css']['link'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

<?php if (count($assets['css']['import']) > 0): ?>
    <style type="text/css">
<?php foreach ($assets['css']['import'] as $css): ?>
        @import url('<?=$css; ?>');
<?php endforeach; ?>
    </style>
<?php endif; ?>

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

</head>

<body class="content-in-edit">
<div id="content-in-edit">
