<?php include $phireHeader; ?>
<?php if ($acl->isAllowed($user->role, 'content', 'search')): ?>
    <form id="content-search-form" action="<?=$phireUri . '/content/' . $tid; ?>" method="get">
        <div><input tabindex="2" type="submit" id="submit" value="Search" /></div>
        <div><input tabindex="1" type="text" name="title" id="title" value="<?=$searchValue; ?>" placeholder="Title" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="content-header"><?=$title; ?></h1>
<?php if (count($content) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/content'; ?>">Back</a></nav>
    </nav>
<?php if ($acl->isAllowed($user->role, 'content', 'process')): ?>
    <form id="contents-form" action="<?=$phireUri . '/content/process/' . $tid; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=title';?>">Title</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=uri';?>">URI</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=created_by_username';?>">Created By</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=created';?>">Created</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=updated';?>">Updated</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=status';?>">Status</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=order';?>">Order</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'content', 'copy')): ?>Copy<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'content', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'content', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="process_content" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($content as $c): ?>
            <tr>
                <td><?=$c->id; ?></td>
                <td><?=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $c->depth) . (($c->depth > 0) ? '&rarr; ' : '') . $c->title; ?></td>
                <td><a class="normal-link" href="<?=BASE_PATH . $c->uri; ?>" target="_blank"><?=BASE_PATH . (($c->uri == '/') ? $c->uri . ' [Index]' : $c->uri); ?></a></td>
                <td><?=$c->created_by_username; ?></td>
                <td><?=date($config->datetime_format, strtotime($c->created)); ?></td>
                <td><?=((null !== $c->updated) ? date($config->datetime_format, strtotime($c->updated)) : null); ?></td>
                <td><?php
switch ($c->status):
    case -1:
        echo '<strong class="red">Unpublished</strong>';
        break;
    case 0:
        echo '<strong class="orange">Draft</strong>';
        break;
    case 1:
        if ((null !== $c->expire) && (strtotime($c->expire) <= time())):
            echo '<strong class="red">Expired</strong>';
        elseif (strtotime($c->publish) > time()):
            echo '<strong class="blue">Scheduled</strong>';
        else:
            echo '<strong class="green">Published</strong>';
        endif;
        break;
endswitch;
?></td>
                <td><?=(int)$c->order; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'content', 'copy')): ?><a class="copy-link" href="<?=$phireUri . '/content/copy/' . $tid . '/' . $c->id; ?>">Copy</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td><?php if (($acl->isAllowed($user->role, 'content', 'edit')) && (($open_authoring) || ((!$open_authoring) && ($c->created_by == $user->id)))): ?><a class="edit-link" href="<?=$phireUri . '/content/edit/' . $tid . '/' . $c->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($acl->isAllowed($user->role, 'content', 'process')) && (($open_authoring) || ((!$open_authoring) && ($c->created_by == $user->id)))): ?><input type="checkbox" name="process_content[]" id="process_content<?=$i++; ?>" value="<?=$c->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'content', 'process')): ?>
        <div id="form-footer">
<?php if (($trash > 0) && ($acl->isAllowed($user->role, 'content', 'trash'))): ?>
            <span><a class="small-link" href="<?=$phireUri . '/content/trash/' . $tid; ?>">Trash (<?=$trash; ?>)</a></span>
<?php endif; ?>
            <select id="content_process_action" name="content_process_action">
                <option value="1">Publish</option>
                <option value="0">Draft</option>
                <option value="-1">Unpublish</option>
                <option value="-2">Trash</option>
                <option value="-3">Remove</option>
            </select>
            <input type="submit" name="submit" class="process-btn" value="Process" />
        </div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/content'; ?>">Back</a></nav>
    </nav>
    <p>
        There is currently no content for this content type.
<?php if (($trash > 0) && ($acl->isAllowed($user->role, 'content', 'trash'))): ?>
        <span><a class="small-link" href="<?=$phireUri . '/content/trash/' . $tid; ?>">Trash (<?=$trash; ?>)</a></span>
<?php endif; ?>
    </p>
<?php endif; ?>
<?php include $phireFooter; ?>