<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($table) && ($acl->isAuth('Phire\Controller\Phire\Config\SitesController', 'migrate'))): ?>
        <a class="export-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/config/migrate"><?php $i18n->_e('Migrate'); ?></a>
<?php endif; ?>
<?php if ($acl->isAuth('Phire\Controller\Phire\Config\SitesController', 'add')): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/config/sites/add">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($form)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/config/sites"><?php $i18n->_e('Back'); ?></a>
<?php echo $form; ?>
<?php if (stripos($title, 'migrate')): ?>
        <h4 class="error" style="clear: both; margin: 10px 0 10px 0;"><br /><?php $i18n->_e('Caution: This action can possibly overwrite content.'); ?></h4>
<?php endif; ?>
<?php elseif (isset($table)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/config"><?php $i18n->_e('Back'); ?></a>
<?php echo $table;
else: ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/config"><?php $i18n->_e('Back'); ?></a>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There are currently no additional sites.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>