<?php include $phireHeader; ?>

    <div class="col-md-12">
    <h1 class="content-header"><?=$title; ?></h1>
<?php if (count($types) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content-types', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/types/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/modules'; ?>">Back</a></nav>
    </nav>
    <div class="table-responsive">
<?php if ($acl->isAllowed($user->role, 'content-types', 'remove')): ?>
    <form id="content-types-form" action="<?=$phireUri . '/content/types/remove'; ?>" method="post">
<?php endif; ?>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th><a href="<?=$phireUri . '/content/types?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/content/types?sort=name';?>">Name</a></th>
                <th><a href="<?=$phireUri . '/content/types?sort=order';?>">Order</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'content-types', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="col-md-1 text-center"><?php if ($acl->isAllowed($user->role, 'content-types', 'remove')): ?><input type="checkbox" name="check_all" id="checkAll" data-name="rm_content_types" value="" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
            </thead>
            <tbody>
<?php $i = 1; ?>
<?php foreach ($types as $type): ?>
            <tr>
                <td><?=$type->id; ?></td>
                <td><?=$type->name; ?></td>
                <td><?=$type->order; ?></td>
                <td><?php if (($acl->isAllowed($user->role, 'content-types', 'edit') && ($acl->isAllowed($user->role, 'content-type-' . $type->id, 'edit')))): ?><a class="edit-link" href="<?=$phireUri . '/content/types/edit/' . $type->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($acl->isAllowed($user->role, 'content-types', 'remove') && ($acl->isAllowed($user->role, 'content-type-' . $type->id, 'remove')))): ?><input type="checkbox" name="rm_content_types[]" id="rm_content_types<?=$i++; ?>" value="<?=$type->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
            </tbody>
        </table>
<?php if ($acl->isAllowed($user->role, 'content-types', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="btn btn-md btn-primary text-uppercase" value="Remove" /></div>
    </form>
    </div>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content-types', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/types/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/modules'; ?>">Back</a></nav>
    </nav>
    <p>There are currently no content types.</p>
<?php endif; ?>
    </div>
<?php include $phireFooter; ?>
