<?php include $phireHeader; ?>

    <div class="col-md-12">
    <h1 class="content-header"><?=$title; ?> : <span id="title-span"><?=$content_title; ?></span></h1>
    <div id="content-owner">
        [<span><a href="<?=BASE_PATH . $uri;?>" id="view-link" target="_blank">View</a></span>] [<span><strong>Created:</strong></span><span><?=$created_by_username; ?></span><span><?=date('M j Y g:i A', strtotime($created)); ?></span><?php if (null !== $updated):?>] [<span><strong>Updated:</strong></span><span><?=$updated_by_username; ?></span><span><?=date('M j Y g:i A', strtotime($updated)); ?></span><?php endif;?>]
    </div>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/' . $tid; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
    </div>
<?php include $phireFooter; ?>
