<?php include $phireHeader; ?>

    <div class="col-md-12">
<?php if (((count($content) > 0) || (isset($_GET['search']))) && $acl->isAllowed($user->role, 'content', 'search')): ?>
    <form id="asset-search-form" action="<?=$phireUri . '/content/' . $tid; ?>" method="get">
        <div><input tabindex="3" type="submit" id="submit" value="Search" /><input type="hidden" name="type_id" value="<?=$tid; ?>" /><input type="hidden" name="search" value="1" /></div>
<?php if (isset($categories) && (count($categories) > 0)): ?>
        <div>
            <select name="category_id" id="category_id">
                <option value="0">----</option>
<?php foreach ($categories as $cid => $category): ?>
                <option value="<?=$cid; ?>"<?=((isset($_GET['category_id']) && ($_GET['category_id'] == $cid)) ? ' selected="selected"' : null); ?>><?=$category; ?></option>
<?php endforeach; ?>
            </select>
        </div>
<?php endif; ?>
        <div><input tabindex="1" type="text" name="title" id="title" value="<?=$searchValue; ?>" placeholder="Title" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="content-header"><?=$title; ?></h1>
<?php if (count($content) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content' . (isset($_GET['type_id']) ? '/' . (int)$_GET['type_id'] : ''); ?>">Back</a></nav>
    </nav>
<?php if (($acl->isAllowed($user->role, 'content', 'process')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'process'))): ?>
    <form id="contents-form" action="<?=$phireUri . '/content/process/' . $tid; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=id' . (($queryString != '') ? '&' . $queryString : '');?>">#</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=title' . (($queryString != '') ? '&' . $queryString : '');?>">Title</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=uri' . (($queryString != '') ? '&' . $queryString : '');?>">URI</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=created_by_username' . (($queryString != '') ? '&' . $queryString : '');?>">Created By</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=created' . (($queryString != '') ? '&' . $queryString : '');?>">Created</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=updated' . (($queryString != '') ? '&' . $queryString : '');?>">Updated</a></th>
                <th><a href="<?=$phireUri . '/content/' . $tid . '?sort=status' . (($queryString != '') ? '&' . $queryString : '');?>">Status</a></th>
<?php if (isset($_GET['category_id'])): ?>
                <th>Category</th>
<?php endif; ?>
                <th class="text-center"><?php if (($acl->isAllowed($user->role, 'content', 'copy')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'copy'))): ?>Copy<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if (($acl->isAllowed($user->role, 'content', 'edit')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'edit'))): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if (($acl->isAllowed($user->role, 'content', 'process')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'process'))): ?><input type="checkbox" name="checkall" id="checkall" value="process_content" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($content as $c): ?>
            <tr>
                <td><?=$c->id; ?></td>
                <td><?=str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $c->depth) . (($c->depth > 0) ? '&rarr; ' : '') . $c->title; ?></td>
                <td><a class="normal-link" href="<?=BASE_PATH . $c->uri; ?>" target="_blank"><?=BASE_PATH . (($c->uri == '/') ? $c->uri . ' [Index]' : $c->uri); ?></a></td>
                <td><?=$c->created_by_username; ?></td>
                <td><?=date('M j Y', strtotime($c->created)); ?></td>
                <td><?=((null !== $c->updated) ? date('M j Y', strtotime($c->updated)) : null); ?></td>
                <td><?php
switch ($c->status):
    case -1:
        echo '<strong class="red">Unpublished</strong>';
        break;
    case 0:
        echo '<strong class="orange">Draft</strong>';
        break;
    case 1:
        if ((null !== $c->expire) && (strtotime($c->expire) <= time())):
            echo '<strong class="red">Expired</strong>';
        elseif (strtotime($c->publish) > time()):
            echo '<strong class="blue">Scheduled</strong>';
        else:
            echo '<strong class="green">Published</strong>';
        endif;
        break;
endswitch;
?></td>
<?php if (isset($_GET['category_id'])): ?>
                <td><?=((isset($c->category_title) && !empty($c->category_title)) ? $c->category_title : null); ?></td>
<?php endif; ?>
                <td><?php if (($acl->isAllowed($user->role, 'content', 'copy')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'copy'))): ?><a class="copy-link" href="<?=$phireUri . '/content/copy/' . $tid . '/' . $c->id; ?>">Copy</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td><?php if (($acl->isAllowed($user->role, 'content', 'edit')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'edit')) && (($open_authoring) || ((!$open_authoring) && ($c->created_by == $user->id)))): ?><a class="edit-link" href="<?=$phireUri . '/content/edit/' . $tid . '/' . $c->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($acl->isAllowed($user->role, 'content', 'process')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'process')) && (($open_authoring) || ((!$open_authoring) && ($c->created_by == $user->id)))): ?><input type="checkbox" name="process_content[]" id="process_content<?=$i++; ?>" value="<?=$c->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if (($acl->isAllowed($user->role, 'content', 'process')) && ($acl->isAllowed($user->role, 'content-type-' . $tid, 'process'))): ?>
        <div id="form-footer">
<?php if (($trash > 0) && ($acl->isAllowed($user->role, 'content', 'trash'))): ?>
            <span><a class="small-link" href="<?=$phireUri . '/content/trash/' . $tid; ?>">Trash (<?=$trash; ?>)</a></span>
<?php endif; ?>
            <select id="content_process_action" name="content_process_action">
                <option value="1">Publish</option>
                <option value="0">Draft</option>
                <option value="-1">Unpublish</option>
                <option value="-2">Trash</option>
                <option value="-3">Remove</option>
            </select>
            <input type="submit" name="submit" class="process-btn" value="Process" />
        </div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content' . (isset($_GET['type_id']) ? '/' . (int)$_GET['type_id'] : ''); ?>">Back</a></nav>
    </nav>
    <p>
        There is currently no content for this content type.<?=(isset($_GET['search']) ? ' Please search again.' : ''); ?>
<?php if (($trash > 0) && ($acl->isAllowed($user->role, 'content', 'trash'))): ?>
        <span><a class="small-link" href="<?=$phireUri . '/content/trash/' . $tid; ?>">Trash (<?=$trash; ?>)</a></span>
<?php endif; ?>
    </p>
<?php endif; ?>
    </div>
<?php include $phireFooter; ?>