<?php include $phireHeader; ?>
<?php if ($acl->isAllowed($user->role, 'content', 'search')): ?>
    <form id="asset-search-form" action="<?=$phireUri . '/content/trash/' . $tid; ?>" method="get">
        <div><input tabindex="2" type="submit" id="submit" value="Search" /></div>
        <div><input tabindex="1" type="text" name="title" id="title" value="" placeholder="Title" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="content-header"><?=$title; ?></h1>
<?php if (count($content) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/content/'. $tid; ?>">Back</a></nav>
    </nav>
<?php if ($acl->isAllowed($user->role, 'content', 'process')): ?>
    <form id="contents-form" action="<?=$phireUri . '/content/process/' . $tid; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/content/trash/' . $tid . '?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/content/trash/' . $tid . '?sort=title';?>">Title</a></th>
                <th><a href="<?=$phireUri . '/content/trash/' . $tid . '?sort=uri';?>">URI</a></th>
                <th><a href="<?=$phireUri . '/content/trash/' . $tid . '?sort=created';?>">Created</a></th>
                <th><a href="<?=$phireUri . '/content/trash/' . $tid . '?sort=updated';?>">Updated</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'content', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="process_content" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($content as $c): ?>
            <tr>
                <td><?=$c->id; ?></td>
                <td><?=$c->title; ?></td>
                <td><a class="normal-link" href="<?=BASE_PATH . $c->uri; ?>" target="_blank"><?=BASE_PATH . (($c->uri == '/') ? $c->uri . ' [Index]' : $c->uri); ?></a></td>
                <td><?=date('M j Y', strtotime($c->created)); ?></td>
                <td><?=((null !== $c->updated) ? date('M j Y', strtotime($c->updated)) : null); ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'content', 'process')): ?><input type="checkbox" name="process_content[]" id="process_content<?=$i++; ?>" value="<?=$c->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'content', 'process')): ?>
        <div id="form-footer">
            <select id="content_process_action" name="content_process_action">
                <option value="1">Publish</option>
                <option value="0">Draft</option>
                <option value="-1">Unpublish</option>
                <option value="-3">Remove</option>
            </select>
            <input type="submit" name="submit" class="process-btn" value="Process" />
        </div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'content', 'add')): ?>
        <nav><a href="<?=$phireUri . '/content/add/' . $tid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/content/'. $tid; ?>">Back</a></nav>
    </nav>
    <p>There are currently nothing in the trash for this content type.</p>
<?php endif; ?>
<?php include $phireFooter; ?>