<?php include $phireHeader; ?>

    <div class="col-md-12">
    <h1 class="content-header"><?=$title; ?></h1>
<?php if (count($types) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Content Types</th>
        </tr>
        </thead>
        <tbody>
<?php $i = 1; ?>
<?php foreach ($types as $type): ?>
<?php if ($acl->isAllowed($user->role, 'content-type-' . $type->id, 'index')): ?>
        <tr>
            <td><a href="<?=$phireUri . '/content/' . $type->id; ?>"><?=$type->name; ?></a></td>
        </tr>
<?php endif; ?>
<?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'content-types', 'add')): ?>
    <nav id="sub-nav">
        <nav><a class="btn-sm btn-info" href="<?=$phireUri . '/content/types/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no content types.</p>
<?php endif; ?>
    </div>
    </div>
<?php include $phireFooter; ?>
