<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($form)): ?>
<?php if (isset($updated)): ?>
        <div id="updated"><?php echo $updated; ?></div>
<?php endif; ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($typeUri) && (!$typeUri) && ($acl->isAuth('Content\Controller\Content\IndexController', 'batch' . (isset($typeId) ? '_' . $typeId : null)))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/batch<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Batch'); ?></a>
<?php endif; ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/index<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Back'); ?></a>
<?php echo $form; ?>
<?php endif; ?>
<?php include $phireFooter; ?>