<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add_' . $typeId)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add/<?php echo $typeId; ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/index/<?php echo $typeId; ?>"><?php $i18n->_e('Back'); ?></a>
<?php if (isset($batchErrors) && (count($batchErrors) > 0)): ?>
        <h4 class="error-div" style="margin-bottom: 5px; height: <?php echo 22 * count($batchErrors); ?>px;"><?php echo implode('<br />', $batchErrors); ?></h4>
<?php endif; ?>
<?php if (isset($form)): ?>
<?php echo $form; ?>
<?php endif; ?>
<?php include $phireFooter; ?>