<?php include $phireHeader; ?>
        <h1 id="content-title" data-title="<?php echo (isset($data_title) ? $data_title : null); ?>"><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($updated)): ?>
        <div id="quick-view">[ <a href="<?php echo ((substr($fullUri, 0, 4) != 'http') ? BASE_PATH . ((!$typeUri) ? CONTENT_PATH . '/media/' : null) . $fullUri : $fullUri); ?>" target="_blank"><?php $i18n->_e('View'); ?></a> ]</div><div id="updated"><?php echo $updated; ?></div><div id="created"><?php echo $created; ?></div>
<?php endif; ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add')): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($typeUri) && (!$typeUri) && ($acl->isAuth('Content\Controller\Content\IndexController', 'batch'))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/batch<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Batch'); ?></a>
<?php endif; ?>
<?php if (isset($form)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/index<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Back'); ?></a>
<?php echo $form; ?>
<?php endif; ?>
<?php include $phireFooter; ?>