<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($table)): ?>
        <form id="content-search-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="get"><div><input type="submit" value="<?php $i18n->_e('Search'); ?>" id="submit" class="search-btn" style="font-size: 10px; margin: 3px 0 3px 3px; padding: 4px 5px 4px 5px; height: 21px; float: right;" name="submit" /><input type="text" name="search_title" id="search-title" size="20" value="<?php echo $searchTitle; ?>" /><?php echo $navSearch; ?><?php echo $catSearch; ?><?php echo $siteSearch; ?></div></form>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($typeUri) && (!$typeUri) && ($acl->isAuth('Content\Controller\Content\IndexController', 'batch' . (isset($typeId) ? '_' . $typeId : null)))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/batch<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Batch'); ?></a>
<?php endif; ?>
<?php echo $table;
elseif (isset($types) && isset($types[0])): ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0" style="border-bottom: solid 1px #ccc;">
            <tr><th class="single-header"><?php $i18n->_e('Content Types'); ?></th></tr>
<?php foreach ($types as $type): ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'index_' . $type->id)): ?>
            <tr><td style="border-left: solid 1px #ccc; border-right: solid 1px #ccc;"><a href="<?php echo BASE_PATH . APP_URI; ?>/content/index/<?php echo $type->id; ?>"><?php echo $type->name;?></a></td></tr>
<?php endif; ?>
<?php endforeach; ?>
        </table>
<?php elseif (isset($type)): ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($typeUri) && (!$typeUri) && ($acl->isAuth('Content\Controller\Content\IndexController', 'batch' . (isset($typeId) ? '_' . $typeId : null)))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/batch<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Batch'); ?></a>
<?php endif; ?>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There is currently no content under the %1 content type.', '<strong>' .$type . '</strong>'); ?><?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add')): ?> <?php $i18n->_e('You can add new content %1here%2 or add a new content type %3here%4.', array('<a href="' . BASE_PATH . APP_URI . '/content/add' . ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null) . '">', '</a>', '<a href="' . BASE_PATH . APP_URI . '/content/types/add">', '</a>')); ?><?php endif; ?></p>
<?php else: ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($typeUri) && (!$typeUri) && ($acl->isAuth('Content\Controller\Content\IndexController', 'batch' . (isset($typeId) ? '_' . $typeId : null)))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/batch<?php echo $typeId; ?>"><?php $i18n->_e('Batch'); ?></a>
<?php endif; ?>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There is currently no content.'); ?><?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add')): ?> <?php $i18n->_e('You can add new content %1here%2 or add a new content type %3here%4.', array('<a href="' . BASE_PATH . APP_URI . '/content/add' . ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null) . '">', '</a>', '<a href="' . BASE_PATH . APP_URI . '/content/types/add">', '</a>')); ?><?php endif; ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>