<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($table)): ?>
        <form id="content-search-form" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="get"><div><input type="submit" value="<?php $i18n->_e('Search'); ?>" id="submit" class="search-btn" style="font-size: 10px; margin: 3px 0 3px 3px; padding: 4px 5px 4px 5px; height: 21px; float: right;" name="submit" /><input type="text" name="search_title" id="search-title" size="20" value="<?php echo $searchTitle; ?>" /><?php echo $navSearch; ?><?php echo $catSearch; ?><?php echo $siteSearch; ?><input type="hidden" name="trash" value="1" /></div></form>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/index<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Back'); ?></a>
<?php echo $table;
else: ?>
<?php if ($acl->isAuth('Content\Controller\Content\IndexController', 'add') && $acl->isAuth('Content\Controller\Content\IndexController', 'add' . (isset($typeId) ? '_' . $typeId : null))): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/add<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/content/index<?php echo ((isset($typeId) && (null !== $typeId)) ? '/' . $typeId : null); ?>"><?php $i18n->_e('Back'); ?></a>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There is currently no content in the trash.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>