<?php include $phireHeader; ?>
        <h1><?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($error)): ?>
        <h4 class="error"><?php echo $error; ?></h4>
<?php else: ?>
<?php if (count($new) > 0): ?>
        <div id="install-nav">
            <a class="install-ext-btn" href="<?php echo BASE_PATH . APP_URI; ?>/extensions/themes/install"><?php $i18n->_e('Install'); ?> (<?php echo count($new); ?>)</a>
            <p><?php $i18n->_e('New themes have been detected. Click the button above to install them.'); ?></p>
        </div>
<?php endif; ?>
<?php if (count($themes) > 0): ?>
        <form id="themes-remove-form" action="<?php echo BASE_PATH . APP_URI; ?>/extensions/themes/process" method="post">
            <table class="data-table" cellpadding="0" cellspacing="0" border="0">
                <tr><th class="first-th">#</th><th style="text-align: center; width: 150px;"><?php $i18n->_e('Screenshot'); ?></th><th><?php $i18n->_e('Theme'); ?></th><th><?php $i18n->_e('Description'); ?></th><th><?php $i18n->_e('Author'); ?></th><th style="text-align: center; width: 10%;"><?php $i18n->_e('Version'); ?></th><th style="text-align: center; width: 10%;"><?php $i18n->_e('Active'); ?></th><th class="last-th"><input type="checkbox" id="checkall" name="checkall" value="remove_themes" /></th></tr>
<?php
foreach ($themes as $theme):
    if ($theme->active):
        $yesChecked = 'checked="checked" ';
        $noChecked  = null;
    else:
        $yesChecked = null;
        $noChecked  = 'checked="checked" ';
    endif;
?>
                <tr><td class="first-td vert-top"><?php echo $theme->id; ?></td><td class="vert-top" style="text-align: center;"><?php echo $theme->screenshot; ?></td><td class="vert-top"><h3 class="theme-header"><?php echo $theme->name; ?></h3></td><td class="vert-top"><?php echo $theme->desc; ?></td><td class="vert-top"><?php echo $theme->author; ?></td><td style="text-align: center;" class="vert-top"><?php echo $theme->version; ?></td><td style="text-align: center;" class="vert-top"><input type="radio" class="radio-btn" name="theme_active" value="<?php echo $theme->id; ?>" <?php echo $yesChecked; ?>/></td><td class="last-td vert-top"><input type="checkbox" name="remove_themes[]" value="<?php echo $theme->id; ?>" /></td></tr>
<?php endforeach; ?>
                <tr class="table-bottom-row"><td colspan="8" class="table-bottom-row"><input type="submit" name="submit" id="submit" class="remove-btn" value="<?php $i18n->_e('Process'); ?>" /></td></tr>
            </table>
        </form>
<?php else: ?>
        <p><?php $i18n->_e('There are currently no themes installed.'); ?></p>
<?php endif; ?>
<?php endif; ?>
<?php include $phireFooter; ?>